#!/bin/bash

check_parameters() {
  local parameter_file=$1
  local system_id=$2
  local changes_file=$3

  # Remove existing changes file
  rm -f "$changes_file"

  # Read the parameter file line by line
  while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines or lines starting with a comment character #
    if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
      continue
    fi

    # Split the line into tagName, recommendedValue, and parameterType
    read -r tagName recommendedValue parameterType <<<"$line"

    # Perform different actions based on the parameterType
    case $parameterType in
      DBM | dbm)
        # Retrieve value
        cmd_value="db2 get dbm cfg | awk -F'=' -v tag=\"$tagName\" '/$tagName/ { gsub(/[[:space:]]+/, \"\", \$2); print \$2 }'"
        value_output=$(eval "$cmd_value" | head -n 1)
        if [ -z "$value_output" ]; then
          value_output="Value is not set"
        fi

        # Compare the current value with the recommended value
        if [ "$value_output" != "$recommendedValue" ]; then
          # Write the change to the changes file
          echo "$tagName is $value_output. Change it to $recommendedValue" >> "$changes_file"
        fi
        ;;
      SID | sid)
        # Retrieve value
        cmd_value="db2 get db cfg for $system_id | awk -F'=' -v tag=\"$tagName\" '/$tagName/ { gsub(/[[:space:]]+/, \"\", \$2); print \$2 }'"
        value_output=$(eval "$cmd_value" | head -n 1)
        if [ -z "$value_output" ]; then
          value_output="Value is not set"
        fi

        # Compare the current value with the recommended value
        if [ "$value_output" != "$recommendedValue" ]; then
          # Write the change to the changes file
          echo "$tagName is $value_output. Change it to $recommendedValue" >> "$changes_file"
        fi
        ;;
      *)
        echo "Invalid parameter type: $parameterType. Skipping..."
        continue
        ;;
    esac
  done < "$parameter_file"

  echo "All parameter checks completed. Please check the $changes_file file for any required changes."
}

# Call the check_parameters() function
check_parameters $1 $2 $3
